import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "./components/basic/navigation/NavigationBar";
import GetSessionProvider from "./provider/GetSessionProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "OneHours",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GetSessionProvider>
          <nav>
            <NavigationBar />
          </nav>
          <main>{children}</main>
        </GetSessionProvider>
      </body>
    </html>
  );
}
