import "./globals.css";
import { Inter } from "next/font/google";
import NavigationBar from "./components/nav-bar/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <NavigationBar />
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
