"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import NavigationBar from "./components/basic/NavigationBar";
import FooterComponent from "./components/basic/footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "OneHours",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <nav>
            <NavigationBar />
          </nav>
          <main>{children}</main>
          {/* <FooterComponent /> */}
        </SessionProvider>
      </body>
    </html>
  );
}
